import { ProviderCatalogSource } from "./types";

const cloudflare: ProviderCatalogSource = {
  id: "cloudflare",
  name: "Cloudflare Workers AI",
  description: "Cloudflare Workers AI - Run AI models at the edge with 10,000 free neurons/day",
  docs: "https://developers.cloudflare.com/workers-ai/",
  auth: {
    type: "bearer",
    keyLabel: "Cloudflare API Token",
    keyUrl: "https://dash.cloudflare.com/profile/api-tokens",
  },
  endpoint: {
    baseUrl: "https://api.cloudflare.com/client/v4/accounts/{ACCOUNT_ID}/ai/v1",
    protocol: "cloudflare",
  },
  accountIdEnv: "CLOUDFLARE_AI_ACCOUNT_ID",
  env: "CLOUDFLARE_AI_API_KEY",
  models: [
    { id: "@cf/baai/bge-base-en-v1.5", upstream: "@cf/baai/bge-base-en-v1.5", free: true, modalities: ["text-to-embedding"], contextWindow: 8192, maxOutputTokens: 4096, capabilities: { streaming: false, tools: false, vision: false, json: false } },
    { id: "@cf/baai/bge-large-en-v1.5", upstream: "@cf/baai/bge-large-en-v1.5", free: true, modalities: ["text-to-embedding"], contextWindow: 8192, maxOutputTokens: 4096, capabilities: { streaming: false, tools: false, vision: false, json: false } },
    { id: "@cf/baai/bge-m3", upstream: "@cf/baai/bge-m3", free: true, modalities: ["text-to-embedding"], contextWindow: 8192, maxOutputTokens: 4096, capabilities: { streaming: false, tools: false, vision: false, json: false } },
    { id: "@cf/baai/bge-reranker-base", upstream: "@cf/baai/bge-reranker-base", free: true, modalities: ["text-to-text"], contextWindow: 8192, maxOutputTokens: 4096, capabilities: { streaming: false, tools: false, vision: false, json: false } },
    { id: "@cf/baai/bge-small-en-v1.5", upstream: "@cf/baai/bge-small-en-v1.5", free: true, modalities: ["text-to-embedding"], contextWindow: 8192, maxOutputTokens: 4096, capabilities: { streaming: false, tools: false, vision: false, json: false } },
    { id: "@cf/google/gemma-3-12b-it", upstream: "@cf/google/gemma-3-12b-it", free: true, modalities: ["text-to-text", "image-to-text"], contextWindow: 128000, maxOutputTokens: 4096, capabilities: { streaming: true, tools: false, vision: true, json: false } },
    { id: "@cf/google/gemma-sea-lion-v4-27b-it", upstream: "@cf/google/gemma-sea-lion-v4-27b-it", free: true, modalities: ["text-to-text"], contextWindow: 8192, maxOutputTokens: 4096, capabilities: { streaming: true, tools: false, vision: false, json: false } },
    { id: "@cf/ibm-granite/granite-4.0-h-micro", upstream: "@cf/ibm-granite/granite-4.0-h-micro", free: true, modalities: ["text-to-text"], contextWindow: 131072, maxOutputTokens: 4096, capabilities: { streaming: true, tools: true, vision: false, json: true } },
    { id: "@cf/meta/llama-3-8b-instruct", upstream: "@cf/meta/llama-3-8b-instruct", free: true, modalities: ["text-to-text"], contextWindow: 8192, maxOutputTokens: 4096, capabilities: { streaming: true, tools: false, vision: false, json: false } },
    { id: "@cf/meta/llama-3-8b-instruct-awq", upstream: "@cf/meta/llama-3-8b-instruct-awq", free: true, modalities: ["text-to-text"], contextWindow: 8192, maxOutputTokens: 4096, capabilities: { streaming: true, tools: false, vision: false, json: false } },
    { id: "@cf/meta/llama-3.1-70b-instruct", upstream: "@cf/meta/llama-3.1-70b-instruct", free: true, modalities: ["text-to-text"], contextWindow: 131072, maxOutputTokens: 4096, capabilities: { streaming: true, tools: false, vision: false, json: false }, benchmark: { livebench: 38.0 } },
    { id: "@cf/meta/llama-3.1-70b-instruct-fp8-fast", upstream: "@cf/meta/llama-3.1-70b-instruct-fp8-fast", free: true, modalities: ["text-to-text"], contextWindow: 131072, maxOutputTokens: 4096, capabilities: { streaming: true, tools: false, vision: false, json: false }, benchmark: { livebench: 38.0 } },
    { id: "@cf/meta/llama-3.1-8b-instruct", upstream: "@cf/meta/llama-3.1-8b-instruct", free: true, modalities: ["text-to-text"], contextWindow: 131072, maxOutputTokens: 4096, capabilities: { streaming: true, tools: false, vision: false, json: false }, benchmark: { livebench: 28.0 } },
    { id: "@cf/meta/llama-3.1-8b-instruct-awq", upstream: "@cf/meta/llama-3.1-8b-instruct-awq", free: true, modalities: ["text-to-text"], contextWindow: 131072, maxOutputTokens: 4096, capabilities: { streaming: true, tools: false, vision: false, json: false }, benchmark: { livebench: 28.0 } },
    { id: "@cf/meta/llama-3.1-8b-instruct-fp8", upstream: "@cf/meta/llama-3.1-8b-instruct-fp8", free: true, modalities: ["text-to-text"], contextWindow: 131072, maxOutputTokens: 4096, capabilities: { streaming: true, tools: false, vision: false, json: false }, benchmark: { livebench: 28.0 } },
    { id: "@cf/meta/llama-3.1-8b-instruct-fp8-fast", upstream: "@cf/meta/llama-3.1-8b-instruct-fp8-fast", free: true, modalities: ["text-to-text"], contextWindow: 131072, maxOutputTokens: 4096, capabilities: { streaming: true, tools: false, vision: false, json: false } },
    { id: "@cf/meta/llama-3.1-8b-instruct-fast", upstream: "@cf/meta/llama-3.1-8b-instruct-fast", free: true, modalities: ["text-to-text"], contextWindow: 131072, maxOutputTokens: 4096, capabilities: { streaming: true, tools: false, vision: false, json: false }, benchmark: { livebench: 28.0 } },
    { id: "@cf/meta/llama-3.2-11b-vision-instruct", upstream: "@cf/meta/llama-3.2-11b-vision-instruct", free: true, modalities: ["text-to-text", "image-to-text"], contextWindow: 131072, maxOutputTokens: 4096, capabilities: { streaming: true, tools: false, vision: true, json: false }, benchmark: { livebench: 26.0 } },
    { id: "@cf/meta/llama-3.2-1b-instruct", upstream: "@cf/meta/llama-3.2-1b-instruct", free: true, modalities: ["text-to-text"], contextWindow: 131072, maxOutputTokens: 4096, capabilities: { streaming: true, tools: false, vision: false, json: false } },
    { id: "@cf/meta/llama-3.2-3b-instruct", upstream: "@cf/meta/llama-3.2-3b-instruct", free: true, modalities: ["text-to-text"], contextWindow: 131072, maxOutputTokens: 4096, capabilities: { streaming: true, tools: false, vision: false, json: false }, benchmark: { livebench: 20.0 } },
    { id: "@cf/meta/llama-3.3-70b-instruct-fp8-fast", upstream: "@cf/meta/llama-3.3-70b-instruct-fp8-fast", free: true, modalities: ["text-to-text"], contextWindow: 131072, maxOutputTokens: 4096, capabilities: { streaming: true, tools: true, vision: false, json: true }, benchmark: { livebench: 40.0 } },
    { id: "@cf/meta/llama-4-scout-17b-16e-instruct", upstream: "@cf/meta/llama-4-scout-17b-16e-instruct", free: true, modalities: ["text-to-text", "image-to-text"], contextWindow: 131072, maxOutputTokens: 4096, capabilities: { streaming: true, tools: true, vision: true, json: true }, benchmark: { livebench: 32.0 } },
    { id: "@cf/meta/llama-guard-3-8b", upstream: "@cf/meta/llama-guard-3-8b", free: true, modalities: ["text-to-text"], contextWindow: 8192, maxOutputTokens: 4096, capabilities: { streaming: true, tools: false, vision: false, json: false } },
    { id: "@cf/meta/m2m100-1.2b", upstream: "@cf/meta/m2m100-1.2b", free: true, modalities: ["text-to-text"], contextWindow: 8192, maxOutputTokens: 4096, capabilities: { streaming: false, tools: false, vision: false, json: false } },
    { id: "@cf/meta/meta-llama-3-8b-instruct", upstream: "@cf/meta/meta-llama-3-8b-instruct", free: true, modalities: ["text-to-text"], contextWindow: 8192, maxOutputTokens: 4096, capabilities: { streaming: true, tools: false, vision: false, json: false } },
    { id: "@cf/mistral/mistral-7b-instruct-v0.1", upstream: "@cf/mistral/mistral-7b-instruct-v0.1", free: true, modalities: ["text-to-text"], contextWindow: 8192, maxOutputTokens: 4096, capabilities: { streaming: true, tools: false, vision: false, json: false } },
    { id: "@cf/mistralai/mistral-small-3.1-24b-instruct", upstream: "@cf/mistralai/mistral-small-3.1-24b-instruct", free: true, modalities: ["text-to-text"], contextWindow: 128000, maxOutputTokens: 4096, capabilities: { streaming: true, tools: true, vision: false, json: true }, benchmark: { livebench: 28.0 } },
    { id: "@cf/nvidia/nemotron-3-120b-a12b", upstream: "@cf/nvidia/nemotron-3-120b-a12b", free: true, modalities: ["text-to-text"], contextWindow: 131072, maxOutputTokens: 4096, capabilities: { streaming: true, tools: true, vision: false, json: true } },
    { id: "@cf/openai/gpt-oss-120b", upstream: "@cf/openai/gpt-oss-120b", free: true, modalities: ["text-to-text"], contextWindow: 131072, maxOutputTokens: 4096, capabilities: { streaming: true, tools: false, vision: false, json: false }, benchmark: { livebench: 46.09 } },
    { id: "@cf/openai/gpt-oss-20b", upstream: "@cf/openai/gpt-oss-20b", free: true, modalities: ["text-to-text"], contextWindow: 131072, maxOutputTokens: 4096, capabilities: { streaming: true, tools: false, vision: false, json: false }, benchmark: { livebench: 38.0 } },
    { id: "@cf/openai/whisper", upstream: "@cf/openai/whisper", free: true, modalities: ["audio-to-text"], contextWindow: 8192, maxOutputTokens: 4096, capabilities: { streaming: false, tools: false, vision: false, json: false } },
    { id: "@cf/openai/whisper-large-v3-turbo", upstream: "@cf/openai/whisper-large-v3-turbo", free: true, modalities: ["audio-to-text"], contextWindow: 8192, maxOutputTokens: 4096, capabilities: { streaming: false, tools: false, vision: false, json: false } },
    { id: "@cf/qwen/qwen3-embedding-0.6b", upstream: "@cf/qwen/qwen3-embedding-0.6b", free: true, modalities: ["text-to-embedding"], contextWindow: 8192, maxOutputTokens: 4096, capabilities: { streaming: false, tools: false, vision: false, json: false } },
    { id: "@cf/qwen/qwen3-30b-a3b-fp8", upstream: "@cf/qwen/qwen3-30b-a3b-fp8", free: true, modalities: ["text-to-text"], contextWindow: 8192, maxOutputTokens: 4096, capabilities: { streaming: true, tools: true, vision: false, json: true }, benchmark: { livebench: 39.01 } },
    { id: "@cf/qwen/qwen2.5-coder-32b-instruct", upstream: "@cf/qwen/qwen2.5-coder-32b-instruct", free: true, modalities: ["text-to-text"], contextWindow: 131072, maxOutputTokens: 4096, capabilities: { streaming: true, tools: false, vision: false, json: false }, benchmark: { livebench: 43.56 } },
    { id: "@cf/qwen/qwq-32b", upstream: "@cf/qwen/qwq-32b", free: true, modalities: ["text-to-text"], contextWindow: 131072, maxOutputTokens: 4096, capabilities: { streaming: true, tools: false, vision: false, json: false }, benchmark: { livebench: 43.56 } },
    { id: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b", upstream: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b", free: true, modalities: ["text-to-text"], contextWindow: 131072, maxOutputTokens: 4096, capabilities: { streaming: true, tools: false, vision: false, json: false }, benchmark: { livebench: 48.0 } },
    { id: "@cf/mistralai/mistral-7b-instruct-v0.2", upstream: "@cf/mistralai/mistral-7b-instruct-v0.2", free: true, modalities: ["text-to-text"], contextWindow: 32768, maxOutputTokens: 4096, capabilities: { streaming: true, tools: false, vision: false, json: false } },
    { id: "@cf/google/gemma-4-26b-a4b-it", upstream: "@cf/google/gemma-4-26b-a4b-it", free: true, modalities: ["text-to-text", "image-to-text"], contextWindow: 131072, maxOutputTokens: 4096, capabilities: { streaming: true, tools: false, vision: true, json: false } },
    { id: "@cf/glm-4.7-flash", upstream: "@cf/glm-4.7-flash", free: true, modalities: ["text-to-text"], contextWindow: 8192, maxOutputTokens: 4096, capabilities: { streaming: true, tools: true, vision: false, json: true }, benchmark: { livebench: 58.09 } },
    { id: "@cf/moonshotai/kimi-k2.5", upstream: "@cf/moonshotai/kimi-k2.5", free: true, modalities: ["text-to-text", "image-to-text"], contextWindow: 131072, maxOutputTokens: 4096, capabilities: { streaming: true, tools: true, vision: true, json: true }, benchmark: { livebench: 48.1 } },
    { id: "@cf/moonshotai/kimi-k2.6", upstream: "@cf/moonshotai/kimi-k2.6", free: true, modalities: ["text-to-text"], contextWindow: 131072, maxOutputTokens: 4096, capabilities: { streaming: true, tools: true, vision: false, json: true } },
  ],
  discovery: {
    authRequired: true,
    rateLimitHeaders: {},
  },
};

export default cloudflare;
