import { ProviderCatalogSource } from "./types";

const gemini: ProviderCatalogSource = {
  id: "gemini",
  name: "Google AI Studio (Gemini)",
  description: "Google's Gemini models with massive context windows and multimodal support",
  docs: "https://ai.google.dev/docs",
  auth: {
    type: "query",
    keyLabel: "Google AI API Key",
    keyUrl: "https://aistudio.google.com/api-keys",
    keyParam: "key",
  },
  endpoint: {
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    protocol: "gemini",
  },
  env: "GEMINI_API_KEY",
  models: [
    {
      id: "gemini-2.5-flash",
      upstream: "gemini-2.5-flash",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 1048576,
      maxOutputTokens: 65536,
      capabilities: { streaming: true, tools: true, vision: true, json: true },
      benchmark: { livebench: 53.09 },
      limits: { requests: { perMinute: 5, perDay: 20 }, tokens: { perMinute: 250000 } },
    },
    {
      id: "gemini-2.5-flash-lite",
      upstream: "gemini-2.5-flash-lite",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 1048576,
      maxOutputTokens: 65536,
      capabilities: { streaming: true, tools: true, vision: true, json: true },
      benchmark: { livebench: 42.56 },
      limits: { requests: { perMinute: 10, perDay: 20 }, tokens: { perMinute: 250000 } },
    },
    {
      id: "gemini-3-flash-preview",
      upstream: "gemini-3-flash-preview",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 1048576,
      maxOutputTokens: 65536,
      capabilities: { streaming: true, tools: true, vision: true, json: true },
      benchmark: { livebench: 72.4 },
      limits: { requests: { perMinute: 5, perDay: 20 }, tokens: { perMinute: 250000 } },
    },
    {
      id: "gemini-robotics-er-1.5-preview",
      upstream: "gemini-robotics-er-1.5-preview",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 1048576,
      maxOutputTokens: 65536,
      capabilities: { streaming: true, tools: false, vision: true, json: false },
      limits: { requests: { perMinute: 10, perDay: 20 }, tokens: { perMinute: 250000 } },
    },
    {
      id: "gemma-3-1b-it",
      upstream: "gemma-3-1b-it",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 32768,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 14400 }, tokens: { perMinute: 15000 } },
    },
    {
      id: "gemma-3-4b-it",
      upstream: "gemma-3-4b-it",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 32768,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 14400 }, tokens: { perMinute: 15000 } },
    },
    {
      id: "gemma-3-12b-it",
      upstream: "gemma-3-12b-it",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 32768,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 14400 }, tokens: { perMinute: 15000 } },
    },
    {
      id: "gemma-3-27b-it",
      upstream: "gemma-3-27b-it",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 14400 }, tokens: { perMinute: 15000 } },
    },
  ],
};

export default gemini;
