import { ProviderCatalogSource } from "./types";

const githubModels: ProviderCatalogSource = {
  id: "github-models",
  name: "GitHub Models",
  description: "Free tier for GitHub users with access to popular models via Azure AI",
  docs: "https://docs.github.com/en/github-models",
  auth: {
    type: "bearer",
    keyLabel: "GitHub Personal Access Token",
    keyUrl: "https://github.com/settings/personal-access-tokens/new",
    keyPrefix: "ghp_",
  },
  endpoint: {
    baseUrl: "https://models.inference.ai.azure.com",
    protocol: "openai",
  },
  limits: {
    requests: { perMinute: 60 },
    tokens: { perDay: 100000 },
    concurrent: 5,
  },
  env: "GITHUB_PERSONAL_TOKEN",
  models: [
    {
      id: "gpt-4.1",
      upstream: "openai/gpt-4.1",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: true, json: true },
      benchmark: { livebench: 45.0 },
    },
    {
      id: "gpt-4.1-mini",
      upstream: "openai/gpt-4.1-mini",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: true, json: true },
      benchmark: { livebench: 38.0 },
    },
    {
      id: "gpt-4.1-nano",
      upstream: "openai/gpt-4.1-nano",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 32.0 },
    },
    {
      id: "gpt-4o",
      upstream: "openai/gpt-4o",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: true, json: true },
      benchmark: { livebench: 44.0 },
    },
    {
      id: "gpt-4o-mini",
      upstream: "openai/gpt-4o-mini",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: true, json: true },
      benchmark: { livebench: 36.0 },
    },
    {
      id: "grok-3",
      upstream: "xai/grok-3",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 42.0 },
    },
    {
      id: "grok-3-mini",
      upstream: "xai/grok-3-mini",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 35.0 },
    },
    {
      id: "DeepSeek-R1-0528",
      upstream: "deepseek/DeepSeek-R1-0528",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: true },
      benchmark: { livebench: 48.0 },
    },
    {
      id: "DeepSeek-R1",
      upstream: "deepseek/DeepSeek-R1",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: true },
      benchmark: { livebench: 48.0 },
    },
    {
      id: "DeepSeek-V3-0324",
      upstream: "deepseek/DeepSeek-V3-0324",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 45.0 },
    },
    {
      id: "MAI-DS-R1",
      upstream: "microsoft/MAI-DS-R1",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: true },
      benchmark: { livebench: 48.0 },
    },
    {
      id: "Phi-4-reasoning",
      upstream: "microsoft/Phi-4-reasoning",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: true },
      benchmark: { livebench: 35.0 },
    },
    {
      id: "Phi-4",
      upstream: "microsoft/Phi-4",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 32.0 },
    },
    {
      id: "Phi-4-multimodal-instruct",
      upstream: "microsoft/Phi-4-multimodal-instruct",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: true, json: true },
      benchmark: { livebench: 30.0 },
    },
    {
      id: "Phi-4-mini-reasoning",
      upstream: "microsoft/Phi-4-mini-reasoning",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: true },
      benchmark: { livebench: 24.0 },
    },
    {
      id: "Phi-4-mini-instruct",
      upstream: "microsoft/Phi-4-mini-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 24.0 },
    },
    {
      id: "Meta-Llama-3.1-405B-Instruct",
      upstream: "meta/Meta-Llama-3.1-405B-Instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 42.0 },
    },
    {
      id: "Llama-3.3-70B-Instruct",
      upstream: "meta/Llama-3.3-70B-Instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 40.0 },
    },
    {
      id: "Llama-3.2-90B-Vision-Instruct",
      upstream: "meta/Llama-3.2-90B-Vision-Instruct",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: true, json: true },
      benchmark: { livebench: 36.0 },
    },
    {
      id: "Llama-3.2-11B-Vision-Instruct",
      upstream: "meta/Llama-3.2-11B-Vision-Instruct",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: true, json: true },
      benchmark: { livebench: 26.0 },
    },
    {
      id: "Llama-4-Maverick-17B-128E-Instruct-FP8",
      upstream: "meta/Llama-4-Maverick-17B-128E-Instruct-FP8",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: true, json: true },
      benchmark: { livebench: 35.0 },
    },
    {
      id: "Llama-4-Scout-17B-16E-Instruct",
      upstream: "meta/Llama-4-Scout-17B-16E-Instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 32.0 },
    },
    {
      id: "Meta-Llama-3.1-8B-Instruct",
      upstream: "meta/Meta-Llama-3.1-8B-Instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 28.0 },
    },
    {
      id: "Cohere-command-r-plus-08-2024",
      upstream: "cohere/Cohere-command-r-plus-08-2024",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 32.0 },
    },
    {
      id: "Cohere-command-r-08-2024",
      upstream: "cohere/Cohere-command-r-08-2024",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 28.0 },
    },
    {
      id: "cohere-command-a",
      upstream: "cohere/cohere-command-a",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 32.0 },
    },
  ],
};

export default githubModels;
