import { ProviderCatalogSource } from "./types";

const groq: ProviderCatalogSource = {
  id: "groq",
  name: "Groq",
  description: "Ultra-fast inference with LPU (Language Processing Unit) technology",
  docs: "https://console.groq.com/docs",
  auth: {
    type: "bearer",
    keyLabel: "Groq API Key",
    keyUrl: "https://console.groq.com/keys",
    keyPrefix: "gsk_",
  },
  endpoint: {
    baseUrl: "https://api.groq.com/openai/v1",
    protocol: "openai",
  },
  limits: {
    requests: { perMinute: 30, perDay: 14400 },
    tokens: { perMinute: 18000, perDay: 1000000 },
  },
  env: "GROQ_API_KEY",
  models: [
    {
      id: "moonshotai/kimi-k2-instruct-0905",
      upstream: "moonshotai/kimi-k2-instruct-0905",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 262144,
      maxOutputTokens: 16384,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 48.1 },
      limits: { requests: { perMinute: 30, perDay: 14400 }, tokens: { perMinute: 6000, perDay: 500000 } },
    },
    {
      id: "moonshotai/kimi-k2-instruct",
      upstream: "moonshotai/kimi-k2-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 16384,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 48.1 },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 7000, perDay: 200000 } },
    },
    {
      id: "openai/gpt-oss-120b",
      upstream: "openai/gpt-oss-120b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 65536,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 46.09 },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 8000, perDay: 200000 } },
    },
    {
      id: "llama-3.3-70b-versatile",
      upstream: "llama-3.3-70b-versatile",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 32768,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 40.0 },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 12000, perDay: 100000 } },
    },
    {
      id: "qwen/qwen3-32b",
      upstream: "qwen/qwen3-32b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 40960,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 43.56 },
      limits: { requests: { perMinute: 60, perDay: 1000 }, tokens: { perMinute: 6000, perDay: 500000 } },
    },
    {
      id: "openai/gpt-oss-20b",
      upstream: "openai/gpt-oss-20b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 65536,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 38.0 },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 8000, perDay: 200000 } },
    },
    {
      id: "meta-llama/llama-4-maverick-17b-128e-instruct",
      upstream: "meta-llama/llama-4-maverick-17b-128e-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 35.0 },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 30000, perDay: 500000 } },
    },
    {
      id: "meta-llama/llama-4-scout-17b-16e-instruct",
      upstream: "meta-llama/llama-4-scout-17b-16e-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 32.0 },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 30000, perDay: 500000 } },
    },
    {
      id: "llama-3.1-8b-instant",
      upstream: "llama-3.1-8b-instant",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 131072,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 28.0 },
      limits: { requests: { perMinute: 30, perDay: 14400 }, tokens: { perMinute: 6000, perDay: 500000 } },
    },
    {
      id: "allam-2-7b",
      upstream: "allam-2-7b",
      free: false,
      modalities: ["text-to-text"],
      contextWindow: 4096,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 7000 }, tokens: { perMinute: 6000, perDay: 500000 } },
    },
    {
      id: "groq/compound",
      upstream: "groq/compound",
      free: true,
      type: "compound",
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 250 }, tokens: { perMinute: 70000 } },
    },
    {
      id: "groq/compound-mini",
      upstream: "groq/compound-mini",
      free: true,
      type: "compound",
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 250 }, tokens: { perMinute: 70000 } },
    },
  ],
  discovery: {
    modelEndpoint: "/v1/models",
    authRequired: true,
    rateLimitHeaders: {
      "x-ratelimit-limit-requests": "Maximum requests per day ceiling",
      "x-ratelimit-limit-tokens": "Maximum tokens per minute ceiling",
      "x-ratelimit-remaining-requests": "Requests remaining today",
      "x-ratelimit-remaining-tokens": "Tokens remaining this minute",
      "x-ratelimit-reset-requests": "Time until daily request reset",
      "x-ratelimit-reset-tokens": "Time until per-minute token reset",
      "retry-after": "Seconds to wait on 429",
    },
    probeEndpoint: "/chat/completions",
    probeMessages: [{ role: "user", content: "hi" }],
  },
};

export default groq;
