import { ProviderCatalogSource } from "./types";

const huggingface: ProviderCatalogSource = {
  id: "huggingface",
  name: "HuggingFace Inference Router",
  description: "Unified gateway to 15+ inference providers through HuggingFace Hub",
  docs: "https://huggingface.co/docs/api-inference/index",
  auth: {
    type: "bearer",
    keyLabel: "HuggingFace Token",
    keyUrl: "https://huggingface.co/settings/tokens",
  },
  endpoint: {
    baseUrl: "https://router.huggingface.co/v1",
    protocol: "openai",
  },
  env: "HUGGINGFACE_API_KEY",
  models: [
    {
      id: "HuggingFaceTB/SmolLM3-3B",
      upstream: "HuggingFaceTB/SmolLM3-3B",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 32768,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      freeVia: ["hf-inference"],
    },
    {
      id: "Qwen/Qwen2.5-VL-72B-Instruct",
      upstream: "Qwen/Qwen2.5-VL-72B-Instruct",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 32768,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: false, vision: true, json: false },
      freeVia: ["hyperbolic"],
    },
    {
      id: "Qwen/Qwen2.5-VL-7B-Instruct",
      upstream: "Qwen/Qwen2.5-VL-7B-Instruct",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 32768,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: false, vision: true, json: false },
      freeVia: ["hyperbolic"],
    },
    {
      id: "Qwen/Qwen2.5-Coder-32B-Instruct",
      upstream: "Qwen/Qwen2.5-Coder-32B-Instruct",
      free: false,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: false, vision: false, json: true },
      benchmark: { livebench: 43.56 },
    },
    {
      id: "Qwen/Qwen3-235B-A22B-Instruct-2507",
      upstream: "Qwen/Qwen3-235B-A22B-Instruct-2507",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 262144,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 48.84 },
      freeVia: ["hyperbolic"],
    },
    {
      id: "Qwen/Qwen3-235B-A22B-Thinking-2507",
      upstream: "Qwen/Qwen3-235B-A22B-Thinking-2507",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 32768,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      benchmark: { livebench: 52.97 },
      freeVia: ["cerebras"],
    },
    {
      id: "Qwen/Qwen3-32B",
      upstream: "Qwen/Qwen3-32B",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 43.56 },
      freeVia: ["groq", "sambanova"],
    },
    {
      id: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
      upstream: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 32768,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      freeVia: ["cerebras", "hyperbolic"],
    },
    {
      id: "Qwen/Qwen3-Next-80B-A3B-Instruct",
      upstream: "Qwen/Qwen3-Next-80B-A3B-Instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 262144,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      freeVia: ["hyperbolic"],
    },
    {
      id: "Qwen/Qwen3-Next-80B-A3B-Thinking",
      upstream: "Qwen/Qwen3-Next-80B-A3B-Thinking",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 262144,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      freeVia: ["hyperbolic"],
    },
    {
      id: "deepseek-ai/DeepSeek-R1",
      upstream: "deepseek-ai/DeepSeek-R1",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 32768,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 48.0 },
      freeVia: ["sambanova", "hyperbolic"],
    },
    {
      id: "deepseek-ai/DeepSeek-R1-0528",
      upstream: "deepseek-ai/DeepSeek-R1-0528",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 48.0 },
      freeVia: ["sambanova", "hyperbolic"],
    },
    {
      id: "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
      upstream: "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      benchmark: { livebench: 48.0 },
      freeVia: ["sambanova"],
    },
    {
      id: "deepseek-ai/DeepSeek-V3.0324",
      upstream: "deepseek-ai/DeepSeek-V3.0324",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 45.0 },
      freeVia: ["sambanova", "hyperbolic"],
    },
    {
      id: "meta-llama/Llama-3.1-8B-Instruct",
      upstream: "meta-llama/Llama-3.1-8B-Instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 32768,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      benchmark: { livebench: 28.0 },
      freeVia: ["cerebras", "sambanova"],
    },
    {
      id: "meta-llama/Llama-3.2-3B-Instruct",
      upstream: "meta-llama/Llama-3.2-3B-Instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131000,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      benchmark: { livebench: 20.0 },
      freeVia: ["hyperbolic"],
    },
    {
      id: "meta-llama/Llama-3.3-70B-Instruct",
      upstream: "meta-llama/Llama-3.3-70B-Instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 40.0 },
      freeVia: ["groq", "sambanova", "hyperbolic"],
    },
    {
      id: "meta-llama/Llama-4-Maverick-17B-128E-Instruct",
      upstream: "meta-llama/Llama-4-Maverick-17B-128E-Instruct",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: true, vision: true, json: true },
      benchmark: { livebench: 35.0 },
      freeVia: ["groq", "sambanova"],
    },
    {
      id: "meta-llama/Llama-4-Scout-17B-16E-Instruct",
      upstream: "meta-llama/Llama-4-Scout-17B-16E-Instruct",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: true, vision: true, json: true },
      benchmark: { livebench: 32.0 },
      freeVia: ["groq"],
    },
    {
      id: "meta-llama/Llama-Guard-4-12B",
      upstream: "meta-llama/Llama-Guard-4-12B",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: false, vision: true, json: false },
      freeVia: ["groq"],
    },
    {
      id: "moonshotai/Kimi-K2-Instruct-0905",
      upstream: "moonshotai/Kimi-K2-Instruct-0905",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 262144,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 48.1 },
      freeVia: ["groq"],
    },
    {
      id: "openai/gpt-oss-120b",
      upstream: "openai/gpt-oss-120b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 46.09 },
      freeVia: ["groq", "cerebras", "sambanova", "hyperbolic"],
    },
    {
      id: "openai/gpt-oss-20b",
      upstream: "openai/gpt-oss-20b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 38.0 },
      freeVia: ["groq", "hyperbolic"],
    },
    {
      id: "openai/gpt-oss-safeguard-20b",
      upstream: "openai/gpt-oss-safeguard-20b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      freeVia: ["groq"],
    },
    {
      id: "tokyotech-llm/Llama-3.3-Swallow-70B-Instruct-v0.4",
      upstream: "tokyotech-llm/Llama-3.3-Swallow-70B-Instruct-v0.4",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: false, vision: false, json: true },
      benchmark: { livebench: 40.0 },
      freeVia: ["sambanova"],
    },
    {
      id: "zai-org/GLM-4.6",
      upstream: "zai-org/GLM-4.6",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 32768,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 55.19 },
      freeVia: ["cerebras"],
    },
    {
      id: "katanemo/Arch-Router-1.5B",
      upstream: "katanemo/Arch-Router-1.5B",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 32768,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: false, vision: false, json: true },
      freeVia: ["hf-inference"],
    },
  ],
};

export default huggingface;
