import { ProviderCatalogSource } from "./types";

const mistral: ProviderCatalogSource = {
  id: "mistral",
  name: "Mistral AI",
  description: "Mistral AI - Open-source and proprietary frontier models from France",
  docs: "https://docs.mistral.ai",
  auth: {
    type: "bearer",
    keyLabel: "Mistral API Key",
    keyUrl: "https://console.mistral.ai/api-keys",
  },
  endpoint: {
    baseUrl: "https://api.mistral.ai/v1",
    protocol: "openai",
  },
  limits: {
    requests: { perMinute: 120 },
    tokens: { perMinute: 500000, perMonth: 1000000000 },
  },
  env: "MISTRAL_API_KEY",
  models: [
    {
      id: "mistral-large-latest",
      upstream: "mistral-large-latest",
      free: false,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 65536,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 87.0 },
      limits: { requests: { perMinute: 120 }, tokens: { perMinute: 300000 } },
    },
    {
      id: "mistral-small-latest",
      upstream: "mistral-small-latest",
      free: false,
      modalities: ["text-to-text"],
      contextWindow: 32768,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 48.0 },
      limits: { requests: { perMinute: 120 }, tokens: { perMinute: 300000 } },
    },
    {
      id: "codestral-latest",
      upstream: "codestral-latest",
      free: false,
      modalities: ["text-to-text"],
      contextWindow: 256000,
      maxOutputTokens: 32000,
      capabilities: { streaming: true, tools: false, vision: false, json: true },
      benchmark: { livebench: 42.0 },
      limits: { requests: { perMinute: 40 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "mistral-embed",
      upstream: "mistral-embed",
      free: false,
      modalities: ["text-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 120 } },
    },
    {
      id: "mistral-large-2411",
      upstream: "mistral-large-2411",
      free: false,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 65536,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 82.0 },
      limits: { requests: { perMinute: 120 }, tokens: { perMinute: 300000 } },
    },
    {
      id: "pixtral-large-latest",
      upstream: "pixtral-large-latest",
      free: false,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 131072,
      capabilities: { streaming: true, tools: true, vision: true, json: true },
      benchmark: { livebench: 69.0 },
      limits: { requests: { perMinute: 120 }, tokens: { perMinute: 300000 } },
    },
    {
      id: "pixtral-12b-2409",
      upstream: "pixtral-12b-2409",
      free: false,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 131072,
      capabilities: { streaming: true, tools: true, vision: true, json: false },
      benchmark: { livebench: 50.0 },
      limits: { requests: { perMinute: 120 }, tokens: { perMinute: 150000 } },
    },
    {
      id: "ministral-3b-2410",
      upstream: "ministral-3b-2410",
      free: false,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 131072,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      benchmark: { livebench: 30.7 },
      limits: { requests: { perMinute: 120 }, tokens: { perMinute: 300000 } },
    },
  ],
  discovery: {
    modelEndpoint: "/v1/models",
    authRequired: true,
    rateLimitHeaders: {},
  },
};

export default mistral;
