import { ProviderCatalogSource } from "./types";

const nvidiaNim: ProviderCatalogSource = {
  id: "nvidia-nim",
  name: "NVIDIA NIM",
  description: "NVIDIA Inference Microservices - Self-hosted & cloud models",
  docs: "https://docs.api.nvidia.com",
  auth: {
    type: "bearer",
    keyLabel: "NVIDIA API Key",
    keyUrl: "https://build.nvidia.com/explore/discover",
    keyPrefix: "nvapi-",
  },
  endpoint: {
    baseUrl: "https://integrate.api.nvidia.com/v1",
    protocol: "openai",
  },
  limits: {
    requests: { perMinute: 30, perDay: 1000 },
  },
  env: "NVIDIA_API_KEY",
  models: [

    {
      id: "01-ai/yi-large",
      upstream: "01-ai/yi-large",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "abacusai/dracarys-llama-3.1-70b-instruct",
      upstream: "abacusai/dracarys-llama-3.1-70b-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "adept/fuyu-8b",
      upstream: "adept/fuyu-8b",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 4096,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: true, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "ai21labs/jamba-1.5-large-instruct",
      upstream: "ai21labs/jamba-1.5-large-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "aisingapore/sea-lion-7b-instruct",
      upstream: "aisingapore/sea-lion-7b-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 4096,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "baai/bge-m3",
      upstream: "baai/bge-m3",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "bigcode/starcoder2-15b",
      upstream: "bigcode/starcoder2-15b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "bytedance/seed-oss-36b-instruct",
      upstream: "bytedance/seed-oss-36b-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "databricks/dbrx-instruct",
      upstream: "databricks/dbrx-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "deepseek-ai/deepseek-coder-6.7b-instruct",
      upstream: "deepseek-ai/deepseek-coder-6.7b-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "deepseek-ai/deepseek-v3.1-terminus",
      upstream: "deepseek-ai/deepseek-v3.1-terminus",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "deepseek-ai/deepseek-v3.2",
      upstream: "deepseek-ai/deepseek-v3.2",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "google/codegemma-1.1-7b",
      upstream: "google/codegemma-1.1-7b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "google/codegemma-7b",
      upstream: "google/codegemma-7b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "google/deplot",
      upstream: "google/deplot",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: true, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "google/gemma-2-2b-it",
      upstream: "google/gemma-2-2b-it",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "google/gemma-2b",
      upstream: "google/gemma-2b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "google/gemma-3-12b-it",
      upstream: "google/gemma-3-12b-it",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 32768,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "google/gemma-3-27b-it",
      upstream: "google/gemma-3-27b-it",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "google/gemma-3-4b-it",
      upstream: "google/gemma-3-4b-it",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 32768,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "google/gemma-3n-e2b-it",
      upstream: "google/gemma-3n-e2b-it",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 32768,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "google/gemma-3n-e4b-it",
      upstream: "google/gemma-3n-e4b-it",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 32768,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "google/gemma-4-31b-it",
      upstream: "google/gemma-4-31b-it",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 262144,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "google/recurrentgemma-2b",
      upstream: "google/recurrentgemma-2b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "ibm/granite-3.0-3b-a800m-instruct",
      upstream: "ibm/granite-3.0-3b-a800m-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 4096,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "ibm/granite-3.0-8b-instruct",
      upstream: "ibm/granite-3.0-8b-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 32768,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "ibm/granite-34b-code-instruct",
      upstream: "ibm/granite-34b-code-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "ibm/granite-8b-code-instruct",
      upstream: "ibm/granite-8b-code-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "meta/codellama-70b",
      upstream: "meta/codellama-70b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "meta/llama-3.1-405b-instruct",
      upstream: "meta/llama-3.1-405b-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "meta/llama-3.1-70b-instruct",
      upstream: "meta/llama-3.1-70b-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "meta/llama-3.1-8b-instruct",
      upstream: "meta/llama-3.1-8b-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "meta/llama-3.2-11b-vision-instruct",
      upstream: "meta/llama-3.2-11b-vision-instruct",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: true, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "meta/llama-3.2-1b-instruct",
      upstream: "meta/llama-3.2-1b-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "meta/llama-3.2-3b-instruct",
      upstream: "meta/llama-3.2-3b-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "meta/llama-3.2-90b-vision-instruct",
      upstream: "meta/llama-3.2-90b-vision-instruct",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: true, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "meta/llama-3.3-70b-instruct",
      upstream: "meta/llama-3.3-70b-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "meta/llama-4-maverick-17b-128e-instruct",
      upstream: "meta/llama-4-maverick-17b-128e-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "meta/llama-guard-4-12b",
      upstream: "meta/llama-guard-4-12b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 4096,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "meta/llama2-70b",
      upstream: "meta/llama2-70b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "microsoft/kosmos-2",
      upstream: "microsoft/kosmos-2",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: true, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "microsoft/phi-3-vision-128k-instruct",
      upstream: "microsoft/phi-3-vision-128k-instruct",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: true, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "microsoft/phi-3.5-moe-instruct",
      upstream: "microsoft/phi-3.5-moe-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "microsoft/phi-4-mini-instruct",
      upstream: "microsoft/phi-4-mini-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "microsoft/phi-4-multimodal-instruct",
      upstream: "microsoft/phi-4-multimodal-instruct",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: true, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "minimaxai/minimax-m2.5",
      upstream: "minimaxai/minimax-m2.5",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "minimaxai/minimax-m2.7",
      upstream: "minimaxai/minimax-m2.7",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "mistralai/codestral-22b-instruct-v0.1",
      upstream: "mistralai/codestral-22b-instruct-v0.1",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "mistralai/devstral-2-123b-instruct-2512",
      upstream: "mistralai/devstral-2-123b-instruct-2512",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "mistralai/magistral-small-2506",
      upstream: "mistralai/magistral-small-2506",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "mistralai/ministral-14b-instruct-2512",
      upstream: "mistralai/ministral-14b-instruct-2512",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "mistralai/mistral-7b-instruct-v0.3",
      upstream: "mistralai/mistral-7b-instruct-v0.3",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "mistralai/mistral-large",
      upstream: "mistralai/mistral-large",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "mistralai/mistral-large-2-instruct",
      upstream: "mistralai/mistral-large-2-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "mistralai/mistral-large-3-675b-instruct-2512",
      upstream: "mistralai/mistral-large-3-675b-instruct-2512",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "mistralai/mistral-medium-3-instruct",
      upstream: "mistralai/mistral-medium-3-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "mistralai/mistral-nemotron",
      upstream: "mistralai/mistral-nemotron",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "mistralai/mistral-small-4-119b-2603",
      upstream: "mistralai/mistral-small-4-119b-2603",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "mistralai/mixtral-8x22b-instruct-v0.1",
      upstream: "mistralai/mixtral-8x22b-instruct-v0.1",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "mistralai/mixtral-8x22b-v0.1",
      upstream: "mistralai/mixtral-8x22b-v0.1",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "mistralai/mixtral-8x7b-instruct-v0.1",
      upstream: "mistralai/mixtral-8x7b-instruct-v0.1",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "moonshotai/kimi-k2-instruct",
      upstream: "moonshotai/kimi-k2-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "moonshotai/kimi-k2-instruct-0905",
      upstream: "moonshotai/kimi-k2-instruct-0905",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "moonshotai/kimi-k2-thinking",
      upstream: "moonshotai/kimi-k2-thinking",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "moonshotai/kimi-k2.5",
      upstream: "moonshotai/kimi-k2.5",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "nv-mistralai/mistral-nemo-12b-instruct",
      upstream: "nv-mistralai/mistral-nemo-12b-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "nvidia/ai-synthetic-video-detector",
      upstream: "nvidia/ai-synthetic-video-detector",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: true, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "nvidia/cosmos-reason2-8b",
      upstream: "nvidia/cosmos-reason2-8b",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: true, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "nvidia/embed-qa-4",
      upstream: "nvidia/embed-qa-4",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "nvidia/gliner-pii",
      upstream: "nvidia/gliner-pii",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 4096,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "nvidia/ising-calibration-1-35b-a3b",
      upstream: "nvidia/ising-calibration-1-35b-a3b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 4096,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "nvidia/llama-3.1-nemoguard-8b-content-safety",
      upstream: "nvidia/llama-3.1-nemoguard-8b-content-safety",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 4096,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "nvidia/llama-3.1-nemoguard-8b-topic-control",
      upstream: "nvidia/llama-3.1-nemoguard-8b-topic-control",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 4096,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "nvidia/llama-3.1-nemotron-51b-instruct",
      upstream: "nvidia/llama-3.1-nemotron-51b-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "nvidia/llama-3.1-nemotron-70b-instruct",
      upstream: "nvidia/llama-3.1-nemotron-70b-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "nvidia/llama-3.1-nemotron-nano-8b-v1",
      upstream: "nvidia/llama-3.1-nemotron-nano-8b-v1",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "nvidia/llama-3.1-nemotron-nano-vl-8b-v1",
      upstream: "nvidia/llama-3.1-nemotron-nano-vl-8b-v1",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: true, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "nvidia/llama-3.1-nemotron-safety-guard-8b-v3",
      upstream: "nvidia/llama-3.1-nemotron-safety-guard-8b-v3",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 4096,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "nvidia/llama-3.1-nemotron-ultra-253b-v1",
      upstream: "nvidia/llama-3.1-nemotron-ultra-253b-v1",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "nvidia/llama-3.2-nemoretriever-1b-vlm-embed-v1",
      upstream: "nvidia/llama-3.2-nemoretriever-1b-vlm-embed-v1",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "nvidia/llama-3.2-nemoretriever-300m-embed-v1",
      upstream: "nvidia/llama-3.2-nemoretriever-300m-embed-v1",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "nvidia/llama-3.2-nv-embedqa-1b-v1",
      upstream: "nvidia/llama-3.2-nv-embedqa-1b-v1",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "nvidia/llama-3.2-nv-embedqa-1b-v2",
      upstream: "nvidia/llama-3.2-nv-embedqa-1b-v2",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "nvidia/llama-3.3-nemotron-super-49b-v1",
      upstream: "nvidia/llama-3.3-nemotron-super-49b-v1",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "nvidia/llama-3.3-nemotron-super-49b-v1.5",
      upstream: "nvidia/llama-3.3-nemotron-super-49b-v1.5",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "nvidia/llama-nemotron-embed-1b-v2",
      upstream: "nvidia/llama-nemotron-embed-1b-v2",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "nvidia/llama-nemotron-embed-vl-1b-v2",
      upstream: "nvidia/llama-nemotron-embed-vl-1b-v2",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "nvidia/llama3-chatqa-1.5-70b",
      upstream: "nvidia/llama3-chatqa-1.5-70b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "nvidia/mistral-nemo-minitron-8b-8k-instruct",
      upstream: "nvidia/mistral-nemo-minitron-8b-8k-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "nvidia/nemoretriever-parse",
      upstream: "nvidia/nemoretriever-parse",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "nvidia/nemotron-3-content-safety",
      upstream: "nvidia/nemotron-3-content-safety",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 4096,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "nvidia/nemotron-3-nano-30b-a3b",
      upstream: "nvidia/nemotron-3-nano-30b-a3b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "nvidia/nemotron-3-super-120b-a12b",
      upstream: "nvidia/nemotron-3-super-120b-a12b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "nvidia/nemotron-4-340b-instruct",
      upstream: "nvidia/nemotron-4-340b-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "nvidia/nemotron-4-340b-reward",
      upstream: "nvidia/nemotron-4-340b-reward",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "nvidia/nemotron-content-safety-reasoning-4b",
      upstream: "nvidia/nemotron-content-safety-reasoning-4b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 4096,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "nvidia/nemotron-mini-4b-instruct",
      upstream: "nvidia/nemotron-mini-4b-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "nvidia/nemotron-nano-12b-v2-vl",
      upstream: "nvidia/nemotron-nano-12b-v2-vl",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: true, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "nvidia/nemotron-nano-3-30b-a3b",
      upstream: "nvidia/nemotron-nano-3-30b-a3b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "nvidia/nemotron-parse",
      upstream: "nvidia/nemotron-parse",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "nvidia/neva-22b",
      upstream: "nvidia/neva-22b",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: true, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "nvidia/nv-embed-v1",
      upstream: "nvidia/nv-embed-v1",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "nvidia/nv-embedcode-7b-v1",
      upstream: "nvidia/nv-embedcode-7b-v1",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "nvidia/nv-embedqa-e5-v5",
      upstream: "nvidia/nv-embedqa-e5-v5",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "nvidia/nv-embedqa-mistral-7b-v2",
      upstream: "nvidia/nv-embedqa-mistral-7b-v2",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "nvidia/nvclip",
      upstream: "nvidia/nvclip",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "nvidia/nvidia-nemotron-nano-9b-v2",
      upstream: "nvidia/nvidia-nemotron-nano-9b-v2",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "nvidia/riva-translate-4b-instruct",
      upstream: "nvidia/riva-translate-4b-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 4096,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
    },
    {
      id: "nvidia/riva-translate-4b-instruct-v1.1",
      upstream: "nvidia/riva-translate-4b-instruct-v1.1",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 4096,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
    },
    {
      id: "openai/gpt-oss-120b",
      upstream: "openai/gpt-oss-120b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "openai/gpt-oss-20b",
      upstream: "openai/gpt-oss-20b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "qwen/qwen2.5-coder-32b-instruct",
      upstream: "qwen/qwen2.5-coder-32b-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "qwen/qwen3-coder-480b-a35b-instruct",
      upstream: "qwen/qwen3-coder-480b-a35b-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "qwen/qwen3-next-80b-a3b-instruct",
      upstream: "qwen/qwen3-next-80b-a3b-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "qwen/qwen3-next-80b-a3b-thinking",
      upstream: "qwen/qwen3-next-80b-a3b-thinking",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "qwen/qwen3.5-122b-a10b",
      upstream: "qwen/qwen3.5-122b-a10b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "qwen/qwen3.5-397b-a17b",
      upstream: "qwen/qwen3.5-397b-a17b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "sarvamai/sarvam-m",
      upstream: "sarvamai/sarvam-m",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "snowflake/arctic-embed-l",
      upstream: "snowflake/arctic-embed-l",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 8192,
      capabilities: { streaming: false, tools: false, vision: false, json: false },
    },
    {
      id: "stepfun-ai/step-3.5-flash",
      upstream: "stepfun-ai/step-3.5-flash",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "stockmark/stockmark-2-100b-instruct",
      upstream: "stockmark/stockmark-2-100b-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "upstage/solar-10.7b-instruct",
      upstream: "upstage/solar-10.7b-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "writer/palmyra-creative-122b",
      upstream: "writer/palmyra-creative-122b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "writer/palmyra-fin-70b-32k",
      upstream: "writer/palmyra-fin-70b-32k",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "writer/palmyra-med-70b",
      upstream: "writer/palmyra-med-70b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "writer/palmyra-med-70b-32k",
      upstream: "writer/palmyra-med-70b-32k",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "z-ai/glm-5.1",
      upstream: "z-ai/glm-5.1",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "z-ai/glm4.7",
      upstream: "z-ai/glm4.7",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "z-ai/glm5",
      upstream: "z-ai/glm5",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: false, vision: false, json: false },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
    {
      id: "zyphra/zamba2-7b-instruct",
      upstream: "zyphra/zamba2-7b-instruct",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
      limits: { requests: { perMinute: 30, perDay: 1000 }, tokens: { perMinute: 100000 } },
    },
  ],
  discovery: {
    modelEndpoint: "/v1/models",
    authRequired: true,
    rateLimitHeaders: {},
  },
};

export default nvidiaNim;
