import { ProviderCatalogSource } from "./types";

const ollamaCloud: ProviderCatalogSource = {
  id: "ollama-cloud",
  name: "Ollama Cloud",
  description: "Run large open-source models in the cloud via Ollama's hosted infrastructure",
  docs: "https://docs.ollama.com/cloud",
  auth: {
    type: "bearer",
    keyLabel: "Ollama API Key",
    keyUrl: "https://ollama.com/settings/keys",
  },
  endpoint: {
    baseUrl: "https://ollama.com/api",
    protocol: "ollama",
  },
  limits: {
    requests: { perMinute: 60 },
    tokens: { perMinute: 100000 },
  },
  env: "OLLAMA_API_KEY",
  models: [
    {
      id: "miniministral-3:8b",
      upstream: "miniministral-3:8b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "gemma4:31b",
      upstream: "gemma4:31b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 262144,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "glm-5",
      upstream: "glm-5",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "kimi-k2:1t",
      upstream: "kimi-k2:1t",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 1048576,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "kimi-k2.5",
      upstream: "kimi-k2.5",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 1048576,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "mistral-large-3:675b",
      upstream: "mistral-large-3:675b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "gemma3:27b",
      upstream: "gemma3:27b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "glm-4.6",
      upstream: "glm-4.6",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "qwen3-coder-next",
      upstream: "qwen3-coder-next",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "deepseek-v3.1:671b",
      upstream: "deepseek-v3.1:671b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "qwen3-vl:235b-instruct",
      upstream: "qwen3-vl:235b-instruct",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: true, json: true },
    },
    {
      id: "devstral-small-2:24b",
      upstream: "devstral-small-2:24b",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "deepseek-v3.2",
      upstream: "deepseek-v3.2",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "gemini-3-flash-preview",
      upstream: "gemini-3-flash-preview",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 1048576,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: true, json: true },
    },
    {
      id: "glm-5.1",
      upstream: "glm-5.1",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
  ],
  discovery: {
    modelEndpoint: "/api/tags",
    authRequired: true,
    rateLimitHeaders: {},
  },
};

export default ollamaCloud;
