import { ProviderCatalogSource } from "./types";

const openrouter: ProviderCatalogSource = {
  id: "openrouter",
  name: "OpenRouter",
  description: "Model aggregator with access to 300+ AI models, including free tier options",
  docs: "https://openrouter.ai/docs",
  auth: {
    type: "bearer",
    keyLabel: "OpenRouter API Key",
    keyUrl: "https://openrouter.ai/settings/keys",
    keyPrefix: "sk-or-v1-",
  },
  endpoint: {
    baseUrl: "https://openrouter.ai/api/v1",
    protocol: "openai",
  },
  limits: {
    requests: { perMinute: 20, perDay: 50 },
  },
  env: "OPENROUTER_API_KEY",
  models: [
    {
      id: "inclusionai/ling-2.6-1t:free",
      upstream: "inclusionai/ling-2.6-1t:free",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 262144,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "tencent/hy3-preview:free",
      upstream: "tencent/hy3-preview:free",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 262144,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "inclusionai/ling-2.6-flash:free",
      upstream: "inclusionai/ling-2.6-flash:free",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 262144,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "baidu/qianfan-ocr-fast:free",
      upstream: "baidu/qianfan-ocr-fast:free",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 65536,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: false, vision: true, json: false },
    },
    {
      id: "google/gemma-4-26b-a4b-it:free",
      upstream: "google/gemma-4-26b-a4b-it:free",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 262144,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "google/gemma-4-31b-it:free",
      upstream: "google/gemma-4-31b-it:free",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 262144,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "nvidia/nemotron-3-super-120b-a12b:free",
      upstream: "nvidia/nemotron-3-super-120b-a12b:free",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 262144,
      maxOutputTokens: 16384,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "minimax/minimax-m2.5:free",
      upstream: "minimax/minimax-m2.5:free",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 196608,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "liquid/lfm-2.5-1.2b-thinking:free",
      upstream: "liquid/lfm-2.5-1.2b-thinking:free",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 32768,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: false, vision: false, json: true },
    },
    {
      id: "liquid/lfm-2.5-1.2b-instruct:free",
      upstream: "liquid/lfm-2.5-1.2b-instruct:free",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 32768,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: false, vision: false, json: true },
    },
    {
      id: "nvidia/nemotron-3-nano-30b-a3b:free",
      upstream: "nvidia/nemotron-3-nano-30b-a3b:free",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 256000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "nvidia/nemotron-nano-12b-v2-vl:free",
      upstream: "nvidia/nemotron-nano-12b-v2-vl:free",
      free: true,
      modalities: ["text-to-text", "image-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: true, json: true },
    },
    {
      id: "qwen/qwen3-next-80b-a3b-instruct:free",
      upstream: "qwen/qwen3-next-80b-a3b-instruct:free",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 262144,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "nvidia/nemotron-nano-9b-v2:free",
      upstream: "nvidia/nemotron-nano-9b-v2:free",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "openai/gpt-oss-120b:free",
      upstream: "openai/gpt-oss-120b:free",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "openai/gpt-oss-20b:free",
      upstream: "openai/gpt-oss-20b:free",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "z-ai/glm-4.5-air:free",
      upstream: "z-ai/glm-4.5-air:free",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "qwen/qwen3-coder:free",
      upstream: "qwen/qwen3-coder:free",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 262000,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "cognitivecomputations/dolphin-mistral-24b-venice-edition:free",
      upstream: "cognitivecomputations/dolphin-mistral-24b-venice-edition:free",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 32768,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: false, vision: false, json: true },
    },
    {
      id: "google/gemma-3n-e2b-it:free",
      upstream: "google/gemma-3n-e2b-it:free",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: false, vision: false, json: true },
    },
    {
      id: "google/gemma-3n-e4b-it:free",
      upstream: "google/gemma-3n-e4b-it:free",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 8192,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: false, vision: false, json: true },
    },
    {
      id: "google/gemma-3-4b-it:free",
      upstream: "google/gemma-3-4b-it:free",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 32768,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "google/gemma-3-12b-it:free",
      upstream: "google/gemma-3-12b-it:free",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 32768,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "google/gemma-3-27b-it:free",
      upstream: "google/gemma-3-27b-it:free",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "meta-llama/llama-3.3-70b-instruct:free",
      upstream: "meta-llama/llama-3.3-70b-instruct:free",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 65536,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "meta-llama/llama-3.2-3b-instruct:free",
      upstream: "meta-llama/llama-3.2-3b-instruct:free",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
    {
      id: "nousresearch/hermes-3-llama-3.1-405b:free",
      upstream: "nousresearch/hermes-3-llama-3.1-405b:free",
      free: true,
      modalities: ["text-to-text"],
      contextWindow: 131072,
      maxOutputTokens: 4096,
      capabilities: { streaming: true, tools: true, vision: false, json: true },
    },
  ],
  discovery: {
    modelEndpoint: "/api/v1/models",
    authRequired: false,
    rateLimitHeaders: {},
  },
};

export default openrouter;
